### ISSUE TITLE
Unable to load file

### ISSUE THREAD

**Issue by al3dv2** [ejones/triposr-texture-gen#2]
I have a error message I use windows 10  :
[Open3D WARNING] Unable to load file ~/output/arcade.obj with ASSIMP

processing mesh
[Open3D WARNING] Creating from empty legacy TriangleMesh.

Traceback (most recent call last):
  File "C:\Users\Shadow\Desktop\triposr-texture-gen\text2texture.py", line 329, in <module>
    tmesh = text2texture(
  File "C:\Users\Shadow\Desktop\triposr-texture-gen\text2texture.py", line 228, in text2texture
    print('computing UV atlas for', len(tmesh.triangle.indices), 'triangles')
KeyError: 'Key indices not found in TensorMap'

**Comment by al3dv2** [comment]
Ok it's because the syntax need to be different on windows for example : 
python text2texture.py C:\Users\Shadow\Desktop\InTeX\data\dragon.glb "a dragon"

**Comment by ejones** [comment]
Hi, are you sure the path is correct? I think I've seen silent errors like this before on missing files.  If it is correct, do you mind sharing the model?
